### ISSUE TITLE
Refactor AnswerInfo

### ISSUE THREAD

**Issue by revenkogrisha** [VlaKiy/QuizTemplate#2]
- public поля принято не использовать, вместо них используются `[SerializeField] private ...`. Если нужен доступ, нужно создать свойство `public int Foo => _foo;` которое даст доступ или написать метод-геттор `public int GetFoo() { }`
- private поля (а тут они должны такими быть) обычно называются с `_`, например `private int _foo;`
- Название поля с префабами кнопок лучше назвать `_buttonPrefabs`, также вместо типа `GameObject` лучше использовать тип `Button`, так как вместо кнопок сюда можно присвоить любой объект.

- `Start()`: вместо разных переменных `int posX` `int posY` лучше использовать одну типа `Vector2 pos`
- `MakeUI()`: `GameObject` тоже лучше заменить на другой тип, переменные нужно называть понятно, не одной буквой. Если нужен компонент `RectTransform`, почему бы его сразу не передовать в метод? `GetComponent<>()` тяжелый метод. Прикол с -1 если честно не понял, нужно это сделать более очевидней, можно сделать отдельный метод который будет ставить по середине, и вызывать его для тех UI, для которых нужно
- `MakeText()`: нету модификатора доступа `private`. Пустой блок else тут совсем не нужен, так не нужно писать. Если ничего не делаем, то тогда его можно было не писать.  А вообще это нарушения одного из принципов программирования. Поведения "Ничего не делаем" как я понял быть не должно, т.е. это ошибка, значит нужно бросить исключение чтобы такого не произошло в процессе игры и ты все пофиксил: `throw new Exception("No Text component on UI");`

Вроде пока все

**Comment by VlaKiy** [comment]
All right
